/**
 * What a theme file is made of. The VALUES ARRIVE AS DATA and none of them live
 * here, which is the rule this package states about itself: "the moment something
 * here needs a NUMBER a designer chose, it is in the wrong package". An emitter
 * renders what it is handed.
 */
export interface ThemeArtefact {
  /** The `data-theme` value, and what the file is called after. */
  readonly name: string;
  /**
   * Every color role, in the order they should be written. A theme is a COMPLETE
   * assignment — a partial one is not a smaller theme, it is a broken one — but
   * completeness is `validateTheme`'s judgement and not the emitter's.
   */
  readonly roles: ReadonlyArray<readonly [string, string]>;
  /**
   * What the BROWSER paints its own controls from — a select's popup, a native
   * checkbox. It reads nothing from the roles, so a dark theme without it ships
   * white native lists on Safari and Firefox.
   */
  readonly scheme?: 'light' | 'dark';
  /** Who rendered it, when that is worth stating in the file. */
  readonly generatedBy?: string;
  /** The `@fmmenchi/tokens` version the role names came from. */
  readonly tokensVersion?: string;
  /** How to check it — an Nx target in a workspace, nothing at all elsewhere. */
  readonly validateWith?: string;
}

/**
 * A theme, as the text of a CSS file.
 *
 * THE FOURTH VERB, and the second emitter. `emitProperties` renders
 * `properties.css` from the contract's names; this renders a theme from a
 * contract's values. Both are here for the reason the barrel gives — "the
 * emitters are here and the files they write are NOT" — and this one was
 * extracted for the same reason `emitProperties` was moved out of tokens: it was
 * unreachable.
 *
 * IT LIVED INSIDE THE NX GENERATOR, as a template literal three lines above a
 * `tree.write`. That put the only renderer of a theme behind the `Tree` API, so
 * nothing else could produce one and nothing could test it except by running a
 * generator against a virtual filesystem. The theme builder wanting to hand
 * somebody a CSS file had exactly two options, and one of them — writing a second
 * template — is the thing the app's own rules forbid: "a second renderer for the
 * same bytes would be two renderings of one decision, and the theme a person
 * downloaded could then differ from the theme installed in their repo".
 *
 * Extracted, that stops being a rule anybody has to remember. One renderer, two
 * callers, identical bytes from identical input — the divergence is not
 * discouraged, it is unavailable.
 *
 * THE HEADER DEGRADES. A generator knows who it is, which tokens version it read
 * and what command checks the result; a download from a web page knows none of
 * that and must not claim it. Each of those three is optional and each takes its
 * sentence with it.
 */
export function emitTheme(theme: ThemeArtefact): string {
  const { name, roles, scheme, generatedBy, tokensVersion, validateWith } =
    theme;

  const attribution = generatedBy
    ? ` — generated by\n * ${generatedBy}${
        tokensVersion ? ` from @fmmenchi/tokens ${tokensVersion}` : ''
      }.`
    : '.';

  // The contrast sentence names the command when there is one, and simply states
  // the requirement when there is not. A file that told a stranger to run an Nx
  // target would be describing a workspace they do not have.
  const checked = validateWith
    ? `Values must be sRGB-displayable literals and every\n * declared pair must keep WCAG contrast — \`${validateWith}\`\n * checks all of it and reports exact ratios. Starting values are the light\n * reference preset.`
    : `Values must be sRGB-displayable literals and every\n * declared pair must keep WCAG contrast.`;

  return `/**
 * \`${name}\` theme for @fmmenchi/ui${attribution}
 *
 * A theme is a COMPLETE assignment of every color role: edit the values,
 * never remove a role. ${checked} Apply with \`<html data-theme="${name}">\`.
 */
[data-theme='${name}'] {
  /* The parts the BROWSER paints — a select's popup, a native checkbox — take
     their palette from \`color-scheme\`, never from the roles below. Without
     this line a dark brand theme ships white native lists on Safari and
     Firefox (a recorded defect of hand-written presets, which is why the
     scaffold states it). Keep it in step with the theme's own lightness. */
  color-scheme: ${scheme ?? 'light'};

${roles.map(([role, value]) => `  ${role}: ${value};`).join('\n')}
}
`;
}
