import { describe, expect, it } from 'vitest';

import { emitTheme } from './emit-theme.js';

/**
 * THIS FILE IS THE POINT OF THE EXTRACTION. The template it exercises used to be a
 * literal inside an Nx generator, three lines above a `tree.write`, so the only way
 * to ask what a theme file says was to run a generator against a virtual
 * filesystem and read a path back out. Nothing about the TEXT could be stated
 * directly. Now it can.
 */

const ROLES = [
  ['--fm-color-primary', 'oklch(50% 0.02 256)'],
  ['--fm-color-primary-foreground', 'oklch(100% 0 0)'],
] as const;

describe('emitTheme', () => {
  it('writes a complete `[data-theme]` block, roles in the order given', () => {
    const css = emitTheme({ name: 'acme', roles: ROLES });

    expect(css).toContain("[data-theme='acme'] {");
    expect(css).toContain('  --fm-color-primary: oklch(50% 0.02 256);');
    expect(css).toContain('  --fm-color-primary-foreground: oklch(100% 0 0);');
    // Order is the caller's, never re-sorted here: a theme's roles are grouped
    // meaningfully in the contract and alphabetising them would throw that away.
    expect(css.indexOf('--fm-color-primary:')).toBeLessThan(
      css.indexOf('--fm-color-primary-foreground:'),
    );
  });

  it('states `color-scheme`, defaulting to light', () => {
    // Not decoration: the browser paints its own controls from this and reads
    // nothing from the roles, so a dark theme without it ships white native lists.
    expect(emitTheme({ name: 'acme', roles: ROLES })).toContain(
      'color-scheme: light;',
    );
    expect(emitTheme({ name: 'noir', roles: ROLES, scheme: 'dark' })).toContain(
      'color-scheme: dark;',
    );
  });

  it('claims a provenance only when it is given one', () => {
    const full = emitTheme({
      name: 'acme',
      roles: ROLES,
      generatedBy: '@fmmenchi/nx-theme-generator:theme',
      tokensVersion: '1.2.3',
      validateWith: 'nx run web:validate-themes',
    });
    expect(full).toContain('generated by');
    expect(full).toContain('from @fmmenchi/tokens 1.2.3.');
    expect(full).toContain('`nx run web:validate-themes`');

    // A download from a web page knows none of those three and must not claim
    // them — a file telling a stranger to run an Nx target describes a workspace
    // they do not have.
    const bare = emitTheme({ name: 'acme', roles: ROLES });
    expect(bare).toContain('`acme` theme for @fmmenchi/ui.');
    expect(bare).not.toContain('generated by');
    expect(bare).not.toContain('@fmmenchi/tokens ');
    expect(bare).not.toContain('nx run');
    // The requirement survives losing the command that checks it.
    expect(bare).toContain('must keep WCAG contrast.');
  });

  it('names the theme everywhere it has to agree with itself', () => {
    const css = emitTheme({ name: 'acme', roles: ROLES });
    // The selector, the header and the usage line: three statements of one name,
    // and a file where they disagreed would be a file nobody could apply.
    expect([...css.matchAll(/acme/g)]).toHaveLength(3);
    expect(css).toContain('<html data-theme="acme">');
  });

  it('emits an empty block for no roles rather than refusing', () => {
    // Completeness is `validateTheme`'s judgement, not the emitter's. An emitter
    // that second-guessed its input would be a second opinion nobody asked for —
    // the rule the theme builder states about itself, applied here.
    const css = emitTheme({ name: 'empty', roles: [] });
    expect(css).toContain("[data-theme='empty'] {");
    expect(css.trimEnd().endsWith('}')).toBe(true);
  });
});
