import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The sidebar IS the docs tree: fully controlled by the structure (and the
// optional _category_.json files) of the source docs folder.
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
