// CULORI IS SAFE HERE for the same reason it is confined to `validate.ts`:
// this module is reachable only from the Node-side test that renders the
// committed JSON, never from the package's main entry, so the colour maths
// stays out of every browser bundle.
import { formatHex, parse as parseColor } from 'culori';
import {
  BORDER_WIDTH_TOKENS,
  BREAKPOINTS,
  COLOR_ROLES,
  CONTAINER_BREAKPOINTS,
  DURATION_TOKENS,
  FONT_TOKENS,
  FONT_WEIGHT_TOKENS,
  RADIUS_TOKENS,
  SIZE_TOKENS,
  SPACE_TOKENS,
  TEXT_TOKENS,
  Z_TOKENS,
} from './tokens.js';

/**
 * THE CONTRACT AS AN INTERCHANGE FILE — W3C Design Tokens (DTCG) JSON,
 * generated from the same two sources as everything else here: the contract
 * arrays for the names, `readVars` over the stylesheets for the values.
 *
 * WHY THIS EXISTS, when the custom property is already the universal port.
 * `var(--fm-*)` reaches every consumer that speaks CSS — Tailwind through the
 * bridge, styled/emotion/inline through `tokenVars` — and none that does not:
 * Figma (Tokens Studio reads DTCG), Style Dictionary (which can emit React
 * Native, Android, iOS, emails), any tool that wants values rather than
 * references. The answer is ONE machine-readable export instead of an adapter
 * per tool, which is the same trade the form port makes: an interchange
 * format, not a collection of integrations.
 *
 * Rendered as strings and committed, kept honest by `dtcg.test.ts` exactly as
 * `properties.css` is — a hand edit fails the ordinary test run.
 *
 * TWO ARTIFACTS, because themes are SETS that stack (the Tokens Studio model):
 * `base.json` is the complete contract with the reference light values;
 * `dark.json` carries only what the dark preset overrides, layered on top by
 * the consumer. A brand theme generated by `nx-theme-generator` is a third set
 * of the same shape.
 *
 * COLOURS ARE THE DRAFT'S STRUCTURED OBJECT — `{ colorSpace, components,
 * hex }` — because the first attempt at this file was removed for shipping
 * `oklch(41% 0.135 255)` as a string, which DTCG `color` never is (the
 * AGENTS.md records the removal). The object keeps the oklch fidelity and the
 * `hex` fallback is computed through culori for readers that only take sRGB.
 * Dimensions and durations stay strings (`"0.25rem"`, `"150ms"`): those forms
 * the recorded bar does not condemn, and they are what Tokens Studio and
 * Style Dictionary read today.
 *
 * THREE FAMILIES ARE DELIBERATELY ABSENT — `shadow`, `ease`, `transition`.
 * Each is a composite the DTCG spec models as a structured object (a shadow
 * list, a cubicBezier's four numbers), and ours include values those objects
 * cannot carry — a modern `linear()` ease, a transition shorthand string.
 * Exporting them as untyped strings would satisfy no reader; parsing them
 * halfway would lie to every reader. They join when a consumer actually needs
 * them, with the parse that consumer can read.
 */

/** A DTCG group: one `$type` at group level, `$value` per token. */
type DtcgGroup = {
  $type?: string;
  $description?: string;
} & Record<string, unknown>;

/**
 * `var(--fm-font-sans)` → the DTCG alias `{font.sans}` — a reference stays a
 * reference. Group is found by longest known prefix, because the names are
 * ambiguous without it: `--fm-font-weight-light` is `font-weight.light`, not
 * `font.weight-light`.
 */
const GROUP_PREFIXES = [
  'font-weight',
  'border-width',
  'color',
  'radius',
  'space',
  'leading',
  'text',
  'font',
  'shadow',
  'size',
  'duration',
  'ease',
  'transition',
  'z',
] as const;

function toAlias(value: string): string | undefined {
  const match = /^var\(--fm-([a-z0-9-]+)\)$/.exec(value.trim());
  if (!match) return undefined;
  const name = match[1];
  const group = GROUP_PREFIXES.find((prefix) => name.startsWith(`${prefix}-`));
  if (!group) return undefined;
  return `{${group}.${name.slice(group.length + 1)}}`;
}

/**
 * A CSS colour → the DTCG color object. `oklch` stays `oklch` — converting to
 * sRGB would clip what the gamut check in `validate.ts` exists to protect —
 * and the `hex` fallback rides along for readers that only take sRGB. A hue
 * left undefined by culori (achromatic: `oklch(100% 0 0)`) becomes `0`, which
 * with zero chroma names the same colour.
 */
function toColor(value: string): {
  colorSpace: 'oklch';
  components: [number, number, number];
  alpha?: number;
  hex: string;
} {
  const parsed = parseColor(value);
  if (parsed === undefined || parsed.mode !== 'oklch') {
    throw new Error(
      `Not an oklch() colour: "${value}". The contract's values are authored ` +
        `in oklch (validate.ts already enforces parsability), so anything else ` +
        `reaching this export is a new notation the converter must learn ` +
        `BEFORE it ships — not silently pass through as a string that claims ` +
        `to be a color token.`,
    );
  }
  const hex = formatHex(parsed);
  return {
    colorSpace: 'oklch',
    components: [parsed.l, parsed.c, parsed.h ?? 0],
    ...(parsed.alpha !== undefined && parsed.alpha !== 1
      ? { alpha: parsed.alpha }
      : {}),
    hex,
  };
}

/** `calc(1.25 / 0.875)` → the number it is — a leading IS a number. */
function toNumber(value: string): number {
  const calc = /^calc\(\s*([\d.]+)\s*\/\s*([\d.]+)\s*\)$/.exec(value);
  if (calc) return Number(calc[1]) / Number(calc[2]);
  const plain = Number(value);
  if (Number.isNaN(plain)) {
    throw new Error(
      `Not a number the DTCG export can carry: "${value}". A numeric token ` +
        `whose value the parser cannot read would ship as NaN — silently null ` +
        `in JSON — so it refuses instead.`,
    );
  }
  return plain;
}

/** A font stack string → the DTCG fontFamily array, quotes unwrapped. */
function toFontFamily(value: string): string[] {
  return value
    .split(',')
    .map((family) => family.trim().replace(/^['"]|['"]$/g, ''));
}

interface GroupSpec {
  group: string;
  type: string;
  names: readonly string[];
  /** `--fm-<varPrefix>-<name>`; defaults to the group name. */
  varPrefix?: string;
  parse?: (value: string) => unknown;
}

const GROUPS: readonly GroupSpec[] = [
  { group: 'color', type: 'color', names: COLOR_ROLES, parse: toColor },
  { group: 'radius', type: 'dimension', names: RADIUS_TOKENS },
  { group: 'space', type: 'dimension', names: SPACE_TOKENS },
  { group: 'text', type: 'dimension', names: TEXT_TOKENS },
  { group: 'leading', type: 'number', names: TEXT_TOKENS, parse: toNumber },
  {
    group: 'font',
    type: 'fontFamily',
    names: FONT_TOKENS,
    parse: toFontFamily,
  },
  {
    group: 'font-weight',
    type: 'fontWeight',
    names: FONT_WEIGHT_TOKENS,
    parse: toNumber,
  },
  { group: 'border-width', type: 'dimension', names: BORDER_WIDTH_TOKENS },
  { group: 'size', type: 'dimension', names: SIZE_TOKENS },
  { group: 'duration', type: 'duration', names: DURATION_TOKENS },
  { group: 'z', type: 'number', names: Z_TOKENS, parse: toNumber },
];

function buildGroup(
  spec: GroupSpec,
  values: ReadonlyMap<string, string>,
  complete: boolean,
): DtcgGroup | undefined {
  const tokens: DtcgGroup = { $type: spec.type };
  let any = false;
  for (const name of spec.names) {
    const variable = `--fm-${spec.varPrefix ?? spec.group}-${name}`;
    const value = values.get(variable);
    if (value === undefined) {
      if (complete) {
        throw new Error(
          `${variable} is in the contract and not in the stylesheet — the ` +
            `export would silently ship an incomplete set.`,
        );
      }
      continue;
    }
    any = true;
    // An alias BEFORE the parser: `var(--fm-font-sans)` is a reference in any
    // group, and handing it to a parser would ship the string dressed as data.
    const alias = toAlias(value);
    tokens[name] = {
      $value: alias ?? (spec.parse ?? ((v: string) => v))(value),
    };
  }
  return any ? tokens : undefined;
}

/**
 * The complete contract with the reference (light) values — `base.json`.
 * Breakpoints ride along from the TS constants: they are contract too, just
 * not custom properties (Tailwind needs them as literals).
 */
export function renderDtcgBase(values: ReadonlyMap<string, string>): string {
  const tree: Record<string, unknown> = {
    $description:
      'The @fmmenchi/tokens contract, reference (light) values. Generated — do not edit; see src/dtcg.ts.',
  };
  for (const spec of GROUPS) {
    tree[spec.group] = buildGroup(spec, values, true);
  }
  tree['breakpoint'] = {
    $type: 'dimension',
    ...Object.fromEntries(
      Object.entries(BREAKPOINTS).map(([name, value]) => [
        name,
        { $value: value },
      ]),
    ),
  };
  tree['container'] = {
    $type: 'dimension',
    ...Object.fromEntries(
      Object.entries(CONTAINER_BREAKPOINTS).map(([name, value]) => [
        name,
        { $value: value },
      ]),
    ),
  };
  return `${JSON.stringify(tree, null, 2)}\n`;
}

/**
 * ONLY what a preset overrides — the dark set, or a brand's. Layered over
 * `base.json` by the consumer, which is how token sets stack.
 */
export function renderDtcgOverrides(
  name: string,
  values: ReadonlyMap<string, string>,
): string {
  const tree: Record<string, unknown> = {
    $description: `The @fmmenchi/tokens ${name} preset — only what it overrides; stack it over base.json. Generated — do not edit; see src/dtcg.ts.`,
  };
  for (const spec of GROUPS) {
    const group = buildGroup(spec, values, false);
    if (group) tree[spec.group] = group;
  }
  return `${JSON.stringify(tree, null, 2)}\n`;
}
