import {
  formatFiles,
  joinPathFragments,
  readProjectConfiguration,
  type Tree,
} from '@nx/devkit';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import { validationGenerator } from '../validation/validation';
import type { ThemeGeneratorSchema } from './schema';

/**
 * Scaffolds a brand theme for @fmmenchi/ui: a COMPLETE `[data-theme='<name>']`
 * assignment of every color role, instantiated from the @fmmenchi/tokens
 * contract INSTALLED in the workspace — so the scaffold is always in sync with
 * the tokens version the app actually uses. Unless --skipValidation, it then
 * calls the `validation` generator to wire the `validate-themes` target
 * (the @fmmenchi/nx-theme-generator:validate executor) so the theme is gated in
 * CI from day one.
 */
export async function themeGenerator(
  tree: Tree,
  options: ThemeGeneratorSchema,
) {
  if (!/^[a-z][a-z0-9-]*$/.test(options.name)) {
    throw new Error(
      `Invalid theme name "${options.name}" — use a lowercase data-theme value (a-z, 0-9, -).`,
    );
  }

  // Resolve the INSTALLED tokens contract (never a bundled copy).
  const req = createRequire(join(tree.root, 'package.json'));
  let varsPath = options.tokensPath;
  let tokensVersion = 'unknown';
  try {
    varsPath = varsPath ?? req.resolve('@fmmenchi/tokens/styles/vars.css');
    const pkgPath = req.resolve('@fmmenchi/tokens/package.json');
    tokensVersion = (
      JSON.parse(readFileSync(pkgPath, 'utf8')) as { version: string }
    ).version;
  } catch {
    if (!varsPath) {
      throw new Error(
        'Could not resolve @fmmenchi/tokens from the workspace root. ' +
          'Install it, or pass --tokensPath=<path to its vars.css>.',
      );
    }
  }

  const vars = readFileSync(varsPath, 'utf8');
  const roles = [
    ...vars.matchAll(/(--fm-color-[a-z0-9-]+)\s*:\s*([^;]+);/g),
  ].map((m) => [m[1], m[2].replace(/\s+/g, ' ').trim()] as const);
  if (roles.length === 0) {
    throw new Error(`No --fm-color-* roles found in ${varsPath}.`);
  }

  const project = readProjectConfiguration(tree, options.project);
  const cssPath = joinPathFragments(
    project.root,
    options.directory ?? 'src/themes',
    `${options.name}.css`,
  );

  const css = `/**
 * \`${options.name}\` theme for @fmmenchi/ui — generated by
 * @fmmenchi/nx-theme-generator:theme from @fmmenchi/tokens ${tokensVersion}.
 *
 * A theme is a COMPLETE assignment of every color role: edit the values,
 * never remove a role. Values must be sRGB-displayable literals and every
 * declared pair must keep WCAG contrast — \`nx run ${options.project}:validate-themes\`
 * checks all of it and reports exact ratios. Starting values are the light
 * reference preset. Apply with \`<html data-theme="${options.name}">\`.
 */
[data-theme='${options.name}'] {
${roles.map(([name, value]) => `  ${name}: ${value};`).join('\n')}
}
`;
  tree.write(cssPath, css);

  if (!options.skipValidation) {
    await validationGenerator(tree, {
      project: options.project,
      themes: [cssPath],
    });
  }
  await formatFiles(tree);
}

export default themeGenerator;
